model:
  n_layer: 1
  n_head: 1
  n_embd: 256
  linear: True
  init_scale: 10

data:
  name: 'window'
  min_num: 1
  max_num: 16
  k: 2
  p: 17
  sep: 17
  cot: False
  num_tokens: 16
  n_train: 256
  n_test: 256
  fixed_len: True

train:
  muon_lr: 0.02
  adamw_lr: 0.0001
  adamw_wd: 0.0
  muon_wd: 0.0
  grad_clip: -1
  num_steps: 100000
  norm_type: "none_rank"
  wandb: True
  save_ckpt: False
  ckpt_freq: 20
